services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Guave\InsertModuleByAliasBundle\:
    resource: ../../../src
    exclude: ../../../src/{Entity,Migrations,Resources,Tests}

  Guave\InsertModuleByAliasBundle\Controller\:
    resource: ../../../src/Controller
    public: true
